name: WDIO health check
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - master
   
jobs:
  build:
   runs-on: macos-latest
   env:
       LT_USERNAME: ${{ secrets.LT_USERNAME }} 
       LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      
      - name: npm dependencies
        run: npm install
        
      - name: Run test
        run: npm run test
