name: WDIO health check
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - master
   
jobs:
  build:
   runs-on: macos-latest
   env:
       LT_USERNAME: ${{ secrets.LT_USERNAME }} 
       LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
   steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: pnpm dependencies
        run: pnpm install
        
      - name: Run test
        run: pnpm run test