name: Publish WDIO Package

on:
  release:
     types: [published]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
