# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test
on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

jobs:
    linux:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x]
        env:
            LT_USERNAME: ${{ secrets.LT_USERNAME }}
            LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test

    macos:
        runs-on: macos-latest
        env:
            LT_USERNAME: ${{ secrets.LT_USERNAME }}
            LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x

            - name: Install dependencies
              run: npm ci --ignore-scripts

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test
